// src/lib/constants.js

// Job Categories
export const jobCategories = [
  "Engineering",
  "Information Technology",
  "Business & Finance",
  "Sales & Marketing",
  "Human Resources & Administration",
  "Healthcare",
  "Science & Research",
  "Design, Media & Arts",
  "Education & Training",
  "Legal",
  "Real Estate",
  "Supply Chain & Transportation",
  "Manufacturing & Production",
  "Customer Service",
  "Social Work",
  "Agriculture",
  "Telecommunications & Networking",
  "Gaming",
  "Entertainment",
  "Security",
  "Culinary",
];

// Technical Skills
export const technicalSkills = [
  // Programming Languages
  "JavaScript",
  "Python",
  "Java",
  "C#",
  "C++",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "Go",
  "Rust",
  "TypeScript",
  "Scala",
  "Perl",
  "R",
  "MATLAB",
  "SQL",
  "Bash/Shell",
  "Powershell",
  "Dart",
  "Assembly",
  "Objective-C",
  "Visual Basic",
  "Groovy",
  "Haskell",
  "Clojure",
  "Elixir",
  "F#",
  "COBOL",
  "Fortran",

  // Web Development
  "HTML",
  "CSS",
  "React",
  "Angular",
  "Vue.js",
  "Svelte",
  "Next.js",
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "Ruby on Rails",
  "Spring Boot",
  "Laravel",
  "ASP.NET",
  "jQuery",
  "Bootstrap",
  "Tailwind CSS",
  "Material UI",
  "Redux",
  "GraphQL",
  "REST API",
  "WebSockets",
  "Web Components",
  "PWA",
  "SASS/SCSS",
  "Webpack",
  "Vite",
  "Babel",
  "ESLint",

  // Mobile Development
  "Android Development",
  "iOS Development",
  "React Native",
  "Flutter",
  "Xamarin",
  "Cordova",
  "Ionic",
  "SwiftUI",
  "Kotlin Multiplatform",
  "Mobile UI Design",
  "AR/VR Development",

  // Database
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Oracle",
  "Microsoft SQL Server",
  "SQLite",
  "Redis",
  "Cassandra",
  "DynamoDB",
  "Firebase",
  "MariaDB",
  "Neo4j",
  "CouchDB",
  "Elasticsearch",
  "Supabase",
  "Prisma",

  // DevOps & Cloud
  "AWS",
  "Azure",
  "Google Cloud",
  "Docker",
  "Kubernetes",
  "Jenkins",
  "GitHub Actions",
  "CircleCI",
  "Travis CI",
  "Terraform",
  "Ansible",
  "Chef",
  "Puppet",
  "Vagrant",
  "Prometheus",
  "Grafana",
  "ELK Stack",
  "Serverless",
  "Nginx",
  "Apache",
  "Linux",
  "Windows Server",
  "CI/CD",
  "Infrastructure as Code",

  // Data Science & AI
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing",
  "Computer Vision",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "scikit-learn",
  "Pandas",
  "NumPy",
  "Data Mining",
  "Big Data",
  "Hadoop",
  "Spark",
  "Tableau",
  "Power BI",
  "Data Visualization",
  "A/B Testing",
  "Statistical Analysis",
  "Reinforcement Learning",

  // Security
  "Cybersecurity",
  "Network Security",
  "Ethical Hacking",
  "Penetration Testing",
  "Cryptography",
  "Security Auditing",
  "Vulnerability Assessment",
  "Firewall Configuration",
  "SIEM",
  "Identity Management",

  // Other Technical
  "Microservices",
  "RESTful Architecture",
  "Agile Methodologies",
  "Scrum",
  "Kanban",
  "UML",
  "Git",
  "SVN",
  "Blockchain",
  "IoT",
  "Embedded Systems",
  "Game Development",
  "Unity",
  "Unreal Engine",
  "Technical Documentation",
  "API Design",
  "System Design",
];

// Soft Skills
export const softSkills = [
  "Communication",
  "Teamwork",
  "Problem-Solving",
  "Critical Thinking",
  "Time Management",
  "Adaptability",
  "Leadership",
  "Creativity",
  "Emotional Intelligence",
  "Work Ethic",
  "Attention to Detail",
  "Conflict Resolution",
  "Decision Making",
  "Negotiation",
  "Stress Management",
  "Interpersonal Skills",
  "Presentation Skills",
  "Public Speaking",
  "Customer Service",
  "Active Listening",
  "Empathy",
  "Patience",
  "Persuasion",
  "Networking",
  "Self-Motivation",
  "Resilience",
  "Cultural Awareness",
  "Project Management",
  "Strategic Planning",
  "Analytical Thinking",
  "Organization",
  "Mentoring",
  "Collaboration",
  "Delegation",
  "Entrepreneurship",
  "Innovation",
  "Relationship Building",
  "Flexibility",
  "Diplomacy",
  "Self-awareness",
  "Integrity",
  "Initiative",
  "Accountability",
];

// Experience Levels
export const experienceLevels = ["Entry", "Intermediate", "Expert"];

// Education Levels
export const educationLevels = [
  "Post-Doctoral",
  "PhD",
  "Master's Degree",
  "Bachelor's Degree",
  "Associate Degree",
  "Diploma",
  "Certificate",
  "Vocational Training",
  "Secondary Education",
  "None",
];

// Education Grades
export const educationGrades = [
  "First Class Honours",
  "Second Class Honours (Upper Division)",
  "Second Class Honours (Lower Division)",
  "Third Class Honours",
  "Pass",
  "Distinction",
  "Credit",
  "Merit",
  "A",
  "A-",
  "B+",
  "B",
  "B-",
  "C+",
  "C",
  "C-",
  "D+",
  "None",
];

// Combined all skills for search
export const allSkills = [...technicalSkills, ...softSkills];
